// Dependency Injection Tokens for Ports

// Repository Ports
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY';
export const SERVICE_REPOSITORY = 'SERVICE_REPOSITORY';
export const RESERVATION_REPOSITORY = 'RESERVATION_REPOSITORY';
export const RESERVATION_STATUS_LOG_REPOSITORY = 'RESERVATION_STATUS_LOG_REPOSITORY';
export const INVITATION_REPOSITORY = 'INVITATION_REPOSITORY';
export const JOB_REPOSITORY = 'JOB_REPOSITORY';

// Infrastructure Ports
export const QUEUE_SERVICE = 'QUEUE_SERVICE';
export const DATABASE_PORT = 'DATABASE_PORT';
export const LOGGER_PORT = 'LOGGER_PORT';
